version: '3'
services:
  memoapp:
    build: ./tomcat
    image: memoapp2-image
    container_name: memoapp2
    ports:
      - 18080:8080
    volumes:
      - ./tomcat/share/logs:/share/logs
    depends_on:
      - memoapp-db
  memoapp-db:
    image: mysql:8.0
    container_name: memoapp-db
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=memoapp_db
      - MYSQL_USER=memoapp
      - MYSQL_PASSWORD=memoapp
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: mysqld --character-set-server=utf8